### PR TITLE
Create samplesnippet

### PR DESCRIPTION
**Pull request by kbragupathy**
Hi CalebFenton,

i have created a new snippet to print the serialized json for your apkfile project. i think it is useful for others. please add it in master branch, 

Thanks
ragu

### CODE REVIEW

**Comment by CalebFenton** [comment]
Hey bro, thanks for this.

It looks like you've added a type adapter for the trove maps and did (improved) the formatting. Does the example code not work as-is? It's been a while since I've touched this.

**Comment by kbragupathy** [comment]
Yes bro, it worked for me, sorry for the late reply

**Comment by CalebFenton** [comment]
Thanks for the response, though it doesn't really answer my question.

**Comment by kbragupathy** [comment]
sorry, i misunderstood. Your example code does not print all the variables in the ApkFile, so i did this trick

**Pull request closed without merging**
